# Generated by Django 3.2.4 on 2021-07-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='interview_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('start_time', models.TextField(max_length=255)),
                ('time_spent_in_minutes', models.IntegerField()),
                ('correct_answers_qty', models.IntegerField()),
                ('incorrect_answers_qty', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('time_provided_in_minutes', models.IntegerField()),
                ('score', models.IntegerField()),
                ('is_completed_all_questions', models.IntegerField()),
            ],
            options={
                'db_table': 'interview_info',
            },
        ),
        migrations.CreateModel(
            name='multiple_choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q_id', models.IntegerField()),
                ('option', models.TextField(max_length=255)),
            ],
            options={
                'db_table': 'multiple_choices',
            },
        ),
        migrations.CreateModel(
            name='Q_A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q', models.TextField(max_length=255)),
                ('A', models.TextField(max_length=255)),
                ('dificulty_level', models.IntegerField()),
            ],
            options={
                'db_table': 'Q_A',
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('email_address', models.TextField(max_length=255)),
                ('password', models.TextField(max_length=255)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
