# Generated by Django 3.2.4 on 2021-07-19 21:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0002_interview_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview_logs',
            name='time',
            field=models.TextField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
