# Generated by Django 3.2.4 on 2021-07-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0003_interview_logs_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview_logs',
            name='is_correct',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
