# Generated by Django 3.2.4 on 2021-07-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0004_interview_logs_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview_logs',
            name='dificulty_level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
