# Generated by Django 3.2.4 on 2021-07-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0008_auditentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditentry',
            name='time',
            field=models.TextField(default='null', max_length=250),
            preserve_default=False,
        ),
    ]
